# Generated by Django 3.2.15 on 2022-11-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0006_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('permissions', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        )
    ]
