from django.urls import path

from . import views

urlpatterns = [
    path('me', views.me, name='me'),
    path('auth/login', views.login, name='login'),
    path('counts', views.count, name='count'),
    path('', views.index, name='index'),
    path('cameras/list', views.camera_list, name='camera.list'),
    path('cameras/report', views.camera_report),
    path('cameras/notification/status/toggle/<int:id>', views.notification_toggle),
    path('cameras/notification/status/active/all', views.all_notification_active),
    path('cameras/notification/status/inactive/all', views.all_notification_inactive),
    path('cameras/notification/create', views.create_notification),
    path('cameras/notification/update/<int:id>', views.update_notification),
    path('cameras/notification/all', views.all_notification),
    path('cameras/notification/all/others', views.all_notification_others),
    path('cameras/notification/delete/<int:id>', views.delete_notification),
    path('crossings/acknowledge/<int:id>', views.acknowledge, name='crossing.history'),
    path('auth/change-password', views.change_password, name='change_password'),
    path('crossings/history', views.crossing_history, name="crossing.history"),
    path('crossings/all', views.all_crossings, name="all_crossings"),
    path('crossings/create', views.create_crossing, name='create_crossing'),
    path('crossings/import', views.import_crossing, name='import_crossing'),
    path('crossings/export', views.export_crossing, name='import_crossing'),
    path('crossings/delete/<int:id>', views.delete_crossing, name='delete_crossing'),
    path('crossings/update/<int:id>', views.update_crossing, name='update_crossing'),
    path('crossings/update-status/<int:id>', views.update_crossing_status, name='update_crossing_status'),
    path('closures', views.closures, name='closures'),
    path('cameras/all', views.cameras, name='cameras'),
    path('cameras/<int:id>', views.camera_single, name='camera_one'),
    path('cameras/create', views.cameras_create, name='cameras_create'),
    path('cameras/update/<int:id>', views.cameras_update, name='cameras_update'),
    path('cameras/delete/<int:id>', views.cameras_delete, name='cameras_delete'),
    path('cameras/upload', views.image_upload, name='camera.image_upload'),
	path('contacts/all', views.all_contacts, name='contacts.all'),
    path('contacts/delete/<int:id>', views.delete_contacts, name='contacts.delete'),
	path('static/<str:name>', views.get_static, name='admin.static'),
    path('static/update/<str:name>', views.update_static, name='admin.static.update'),
    path('users/all', views.get_users, name='users.all'),
    path('users/create', views.add_user, name='users.create'),
    path('users/update/<int:id>', views.edit_user, name='users.update'),
    path('users/delete/<int:id>', views.delete_user, name='users.delete'),
    path('permissions', views.get_permissions, name='users.permissions'),
    path('roles/all', views.get_roles, name='admin.roles'),
    path('roles/create', views.create_roles, name='admin.create'),
    path('roles/update/<int:id>', views.update_roles, name='admin.update'),
    path('roles/delete/<int:id>', views.delete_roles, name='admin.delete'),
    path('trafic', views.trafic_stat, name='admin.trafic')
]
